import { Book, BOOK_EMOJIS, GENRES } from "./types";

export const SAMPLE_BOOKS: Book[] = [
  // FINISHED THRILLERS (Establish success pattern)
  {
    id: "1",
    title: "Silent Patient",
    author: "Alex Michaelides",
    total_pages: 336,
    genre: ["Thriller", "Fiction"],
    status: "Finished",
    progress_pages: 336,
    progress_percent: 100,
    abandon_reasons: [],
    start_date: "2023-01-15",
    cover_emoji: "🤐",
  },
  {
    id: "2",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    total_pages: 480,
    genre: ["Thriller", "Fiction"],
    status: "Finished",
    progress_pages: 480,
    progress_percent: 100,
    abandon_reasons: [],
    start_date: "2023-02-10",
    cover_emoji: "🗝️",
  },
  {
    id: "3",
    title: "Gone Girl",
    author: "Gillian Flynn",
    total_pages: 422,
    genre: ["Thriller", "Fiction"],
    status: "Finished",
    progress_pages: 422,
    progress_percent: 100,
    abandon_reasons: [],
    start_date: "2023-03-05",
    cover_emoji: "👱‍♀️",
  },

  // ABANDONED NON-FICTION (Establish quit pattern at ~40%)
  {
    id: "4",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    total_pages: 499,
    genre: ["Non-Fiction", "Psychology"],
    status: "Abandoned",
    progress_pages: 180,
    progress_percent: 36,
    abandon_reasons: ["Too dense/complex", "Lost interest"],
    start_date: "2023-04-01",
    abandon_date: "2023-04-20",
    cover_emoji: "🧠",
  },
  {
    id: "5",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    total_pages: 443,
    genre: ["Non-Fiction", "History"],
    status: "Abandoned",
    progress_pages: 190,
    progress_percent: 43,
    abandon_reasons: ["Too dense/complex"],
    start_date: "2023-05-10",
    abandon_date: "2023-05-25",
    cover_emoji: "🐒",
  },

  // CURRENT READING (For Testing Coach)
  {
    id: "6",
    title: "Dark Matter",
    author: "Blake Crouch",
    total_pages: 352,
    genre: ["Sci-Fi", "Thriller"],
    status: "Reading",
    progress_pages: 200,
    progress_percent: 57, // Past 50% + Genre Match (Thriller) -> Should be PUSH
    abandon_reasons: [],
    start_date: "2023-10-01",
    cover_emoji: "🌌",
  },
  {
    id: "7",
    title: "Principles",
    author: "Ray Dalio",
    total_pages: 592,
    genre: ["Non-Fiction", "Business"],
    status: "Reading",
    progress_pages: 100,
    progress_percent: 17, // Early + Length Mismatch + Genre Mismatch -> Should be QUIT or NEUTRAL
    abandon_reasons: [],
    start_date: "2023-10-05",
    cover_emoji: "📈",
  },

  // MORE HISTORY
  {
    id: "8",
    title: "Project Hail Mary",
    author: "Andy Weir",
    total_pages: 496,
    genre: ["Sci-Fi", "Fiction"],
    status: "Finished",
    progress_pages: 496,
    progress_percent: 100,
    abandon_reasons: [],
    start_date: "2023-06-15",
    cover_emoji: "🚀",
  },
  {
    id: "9",
    title: "Dune",
    author: "Frank Herbert",
    total_pages: 412,
    genre: ["Sci-Fi", "Fiction"],
    status: "Abandoned",
    progress_pages: 150,
    progress_percent: 36, // Reinforces ~36-43% quit zone
    abandon_reasons: ["Too slow", "Hard to follow"],
    start_date: "2023-07-20",
    abandon_date: "2023-08-05",
    cover_emoji: "🏜️",
  },
  {
    id: "10",
    title: "Atomic Habits",
    author: "James Clear",
    total_pages: 320,
    genre: ["Self-Help", "Non-Fiction"],
    status: "Finished",
    progress_pages: 320,
    progress_percent: 100,
    abandon_reasons: [],
    start_date: "2023-09-01",
    cover_emoji: "⚛️",
  }
];
